name: .NET Build And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@v3
        
      - name: Run Infrastructure
        run: docker-compose -f "docker-compose-infrastructure.yml" up -d
        
      - name: Run Build and Testing
        run: docker-compose -f "docker-compose-build-and-test.yml" up --exit-code-from integration-tests
