name: .NET Build And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@v3
        
      - name: Sleep on it !!
        run: sleep 30
