name: .NET Build And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Running Testings
        run: docker-compose -f "docker-compose-all-in-one.yml" up --exit-code-from integration-tests
        
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose-all-in-one.yml" down
