name: .NET Build And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Running Testing Infrastructure
        run: docker-compose -f "docker-compose-db.yml" up -d --build
        
      - name: Rung Testing
        run: docker-compose -f "docker-compose-tests.yml" up -d --build
        
      - name: Showing Test Result
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: "TestResults/test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
        
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose-db.yml" down --remove-orphans
